name: Floppy CI

on:
  push:
    branches: "main"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    # - name: Install dependency
    #   run: npm install

    - name: Print colorful text with smile
      run: echo -e "\033[32mOperations were carried out successfully\033[0m" 

#Konstantin Piatigorskii
