name: Floppy CI

on:
  push:
    branches: "main"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    # - name: Install dependency
    #   run: npm install

    - name: Set the environment variables
      run: |
        GREEN='\033[0;32m'
        NC='\033[0m' # No Color
        echo -e "${GREEN}I love Github Actions!${NC}"

#Konstantin Piatigorskii
